-- Generated by nwg-displays on 2026-09-16 at 18:25:11. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.0",
    position = "1920x360",
    scale = 1.5,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@55.0",
    position = "0x0",
    scale = 1.0,
    vrr = 0
})
